name: Coveralls

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CI: true

jobs:
  test:
    name: Node.js Tests on ${{ matrix.os }} with Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [21]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run lint
        working-directory: backend
        run: npm run lint

      - name: Run tests with coverage
        working-directory: backend
        run: npm run test-cov

      - name: Verify Coveralls Token
        run: echo "${{ secrets.COVERALLS_REPO_TOKEN }}"

      - name: Upload coverage to Coveralls
        working-directory: backend
        run: cat ./coverage/lcov.info | node ./bin/coveralls.js
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_SERVICE_NAME: CI-pipeline
          COVERALLS_SERVICE_JOB_ID: ${{ github.run_id }}
          COVERALLS_SERVICE_JOB_NUMBER: ${{ github.run_number }}
          COVERALLS_FLAG_NAME: ${{ matrix.os }}-node-${{ matrix.node }}
          COVERALLS_PARALLEL: true
          NODE_COVERALLS_DEBUG: 1

  finish:
    name: Finalize Coveralls Job
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Notify Coveralls job completion
        run: |
          curl -kv -d 'payload[build_num]=${{ github.run_id }}&payload[status]=done' https://coveralls.io/webhook?repo_token=${{ secrets.COVERALLS_REPO_TOKEN }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
